name: Run Every 10 Minutes After Manual Trigger

on:
  workflow_run:
    workflows: ["Manual Trigger Workflow"]
    types:
      - completed

jobs:
  run_every_10_minutes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set start time
        id: set_start_time
        run: echo "::set-output name=start_time::$(date +%s)"

      - name: Run Job Every 10 Minutes
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          current_time=$(date +%s)
          start_time=${{ steps.set_start_time.outputs.start_time }}
          elapsed_time=$((current_time - start_time))
          
          if [ $elapsed_time -lt 3600 ]; then
            echo "Continue running the job"
            # Add your job steps here
          else
            echo "Stop running the job after 1 hour"
          fi
