name: Run Every 10 Minutes 5 Times

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  workflow_run:
    workflows: ["manual-trigger"]
    types:
      - completed

jobs:
  runJob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Job
      run: |
        echo "Executing job..."
        # Your job steps go here

  checkRunCount:
    needs: runJob
    runs-on: ubuntu-latest

    steps:
    - name: Check Run Count
      id: checkRunCount
      run: echo "::set-output name=runCount::${{ github.event.workflow_run.conclusion == 'success' && github.run_number <= 5 }}"

  triggerNextRun:
    needs: checkRunCount
    if: ${{ steps.checkRunCount.outputs.runCount == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Next Run
      run: |
        echo "Triggering the next run..."
        # Additional steps for the next run
